# Generated by Django 4.2.30 on 2026-04-17 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_book_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='book',
            name='published_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AddConstraint(
            model_name='book',
            constraint=models.UniqueConstraint(fields=('title', 'author', 'published_year'), name='unique_book_record'),
        ),
    ]
